title: My Health Haven
description: Your trusted space for health, wellness, and balance. Here, we believe that small lifestyle choices create big transformations. From mindful nutrition tips and simple fitness routines to stress management and self-care, we’re here to guide you toward living your healthiest, happiest life.
baseurl: "/myhealthhaven.github.io" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://ebenezer129dotcom.github.io" # change this to the base hostname & protocol for your site

# Pages that should appear in the header menu
header_pages:
  - index.md
  - nutrition.md
  - wellness.md
  - fitness.md
  - about.md
google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: lorepirri
image: /thumbnail-jumbo.png
twitter:
  username: lorepirri

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']





