title: My Health Haven
tagline: "Simple steps to a healthier, happier you"
description: "Your trusted space for simple, reliable, and inspiring health tips. Discover wellness practices, nutrition ideas, and self-care guides to live a healthier, happier life."

# Navigation menu (these pages must exist in your repo)
header_pages:
  - index.md
  - about.md
  - contact.md
